name: Publish

on:
  push:
    branches:
      - v3

jobs:
  publish:
    if: ${{ startsWith(github.event.head_commit.message, 'chore(release):') }}
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v3
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npx pnpm install
          npm run build
          npm run test

          # Publish package
          if $IS_BETA; then
            npm run publish-package -- --tag next
          else
            npm run publish-package
          fi

          # Publish docs
          npm run publish-docs -- --user "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          IS_BETA: ${{ contains(github.event.head_commit.message, 'beta') }}
