name: Publish

on:
  push:
    branches:
      - v3

jobs:
  publish:
    # if: |
    #   startsWith(github.event.push.commits[0].message, 'chore(release):')
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v3
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: |
          echo $XX
          echo "$IS_BETA"
          if [[ $IS_BETA -gt true ]]
          then
            echo "is beta"
          else
            echo "not beta"
          fi
          # 1 chore(release): test
          # npx pnpm install
          # npm run build
          # npm run test
          # cd ./lib
          # npm publish
        env:
          XX: ${{ toJSON(github.event) }}
          IS_BETA: ${{ contains(github.event.commits[0].message, 'beta') }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
