name: Test

on:
  push:
    branches:
      - v3

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v3
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ hashFiles('pnpm-lock.yaml') }}
      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: npx pnpm install
      - run: |
          npm run build
          npm run test-with-coverage
          npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
