name: Test

on:
  push:
    branches:
      - v3

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v3
      - run: |
          npx pnpm install
          npm run build
          npm run test-with-coverage
          npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
